# Generated by Django 2.1.5 on 2019-02-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='customer_answer',
            field=models.CharField(max_length=50),
        ),
    ]
