# Generated by Django 2.1.5 on 2019-02-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20190209_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
